/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void knbLFO_turn(GKnob source, GEvent event) { //_CODE_:knbLFO:572973:
    //println("knbLFO - GKnob >> GEvent." + event + " @ " + millis());
} //_CODE_:knbLFO:572973:

public void textLFO_change(GTextField source, GEvent event) { //_CODE_:textLFO:405335:
  println("textLFO - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:textLFO:405335:

public void LFOEnable_click(GImageToggleButton source, GEvent event) { //_CODE_:LFOEnable:631929:
  println(source.getState());
  RegLFO = byte((RegLFO & 0xF7) | byte(source.getState() << 3));
  bRegLFOChanged = true;
} //_CODE_:LFOEnable:631929:

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:textfield1:589525:
  println("textfield1 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:textfield1:589525:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  knbLFO = new GKnob(this, 40, 40, 60, 60, 0.8);
  knbLFO.setTurnRange(110, 70);
  knbLFO.setTurnMode(GKnob.CTRL_ANGULAR);
  knbLFO.setShowArcOnly(false);
  knbLFO.setOverArcOnly(false);
  knbLFO.setIncludeOverBezel(true);
  knbLFO.setShowTrack(true);
  knbLFO.setLimits(1.0, 1.0, 8.0);
  knbLFO.setNbrTicks(8);
  knbLFO.setStickToTicks(true);
  knbLFO.setShowTicks(true);
  knbLFO.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  knbLFO.setOpaque(false);
  knbLFO.addEventHandler(this, "knbLFO_turn");
  lblLFO = new GLabel(this, 30, 10, 80, 20);
  lblLFO.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lblLFO.setText("LFO");
  lblLFO.setTextBold();
  lblLFO.setOpaque(false);
  textLFO = new GTextField(this, 50, 110, 40, 20, G4P.SCROLLBARS_NONE);
  textLFO.setText("0");
  textLFO.setOpaque(true);
  textLFO.addEventHandler(this, "textLFO_change");
  LFOEnable = new GImageToggleButton(this, 50, 140);
  LFOEnable.addEventHandler(this, "LFOEnable_click");
  lblOff = new GLabel(this, 50, 190, 40, 20);
  lblOff.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lblOff.setText("Off");
  lblOff.setOpaque(false);
  textfield1 = new GTextField(this, 150, 50, 160, 30, G4P.SCROLLBARS_NONE);
  textfield1.setOpaque(true);
  textfield1.addEventHandler(this, "textfield1_change1");
}

// Variable declarations 
// autogenerated do not edit
GKnob knbLFO; 
GLabel lblLFO; 
GTextField textLFO; 
GImageToggleButton LFOEnable; 
GLabel lblOff; 
GTextField textfield1; 
